[package]
name = "pixelmatch-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"


[package.metadata.wasm-pack.profile.release]
wasm-opt = false